services:
  voicepeak:
    build:
      context: ./voicepeak/
      dockerfile: Dockerfile
    container_name: voicepeak_setup
    ports:
      - "3000:3000"
    volumes:
      - ./voicepeak/mountspace:/mountspace/
  orchestrator:
    build: 
      context: .
      dockerfile: apps/stream_orchestrator/Dockerfile
    container_name: stream_orchestrator
    command: ["http://192.168.68.16:8888"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./education.json:/app/education.json
      - ./.env:/app/.env
      - ./voicepeak/mountspace/:/mountspace/
      - ./video/:/app/video/
    shm_size: "1gb"
    #restart: unless-stopped
  hub:
    build: 
      context: .
      dockerfile: apps/hub/Dockerfile
    container_name: hub
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./video/:/app/apps/hub/video/
    ports:
      - "8888:8888"
    shm_size: "1gb"
    #restart: unless-stopped
  voicevox_connector:
    build:
      context: .
      dockerfile: apps/voicevox_connector/Dockerfile
    container_name: voicevox_connector
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    ports:
      - "50020:50020"
    shm_size: "1gb"
    #restart: unless-stopped
