[x]
keywords = ["x", "twitter"]
task = "https://x.com/boxfish_jp"

[github]
keywords = ["github"]
task = "https://github.com/boxfish-jp"

["annict"]
keywords = ["annict"]
task = "https://annict.com/@boxfish_jp"

["今季のアニメ"]
keywords = ["今季のアニメ", "今季アニメ", "今期のアニメ", "今期アニメ"]
task = "https://annict.com/@boxfish_jp/watching"

["アニソン"]
keywords= ["アニソン"]
task = "https://open.spotify.com/playlist/6k1uAvFFTknwimCs8QZCkm?si=1c043078d64542e1"

["壁紙"]
keywords = ["壁紙"]
task = "https://clumsy-fight-294.notion.site/1851cddf59bc8083b5f6ccf222c265ac"

["do"]
keywords = ["do", "やれ"]
task = "https://youtu.be/JV3KOJ_Z4Vs?si=dKcVDMkcWcRNwRak"
